spring:
  application:
    name: API-GATEWAY

server:
  port: 9000

cloud:
  gateway:
    routes:
      - id: authService
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/auth/**

      - id: productService
        uri: lb://PRODUCT-SERVICE
        predicates:
          - Path=/product/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
