server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            # AUTH SERVICE
            - id: authService
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # PRODUCT SERVICE
            - id: productService
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
